# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Data Blog Time" 
email: yuexizeng77@gmail.com 
description: "This is a little blog site about some Data thoughts" 
baseurl: "/yuexizeng.github.io" # the name of the repository 
url: "https://zyuexi2.github.io/yuexizeng.github.io/" #  change this to "https://<your-github-username>.github.io"
image: https://github.com/zyuexi2/yuexizeng.github.io/blob/main/carl-heyerdahl-KE0nC8-58MQ-unsplash.jpg
author: Yuexi Zeng
copyright: YZ # Your initials or what you want the copyright to be.  Leave empty for no copyright
footer_description: 'The default image for the site header is a random image from 
        <a href="https://github.com/zyuexi2/yuexizeng.github.io/blob/main/firmbee-com-jrh5lAq-mIs-unsplash.jpg" target="_blank"> Unsplash</a>. 
        The default image for the blog post is from
        <a href="https://github.com/zyuexi2/yuexizeng.github.io/blob/main/isaac-smith-6EnTPvPPL6I-unsplash.jpg" target="_blank"
        >Unsplash by Issac Smith</a>. Students in Stat 386 using this theme should replace both images 
        with their own.'


# Social media users names.  Leave fields blank that you don't want displayed
twitter_username: 
github_username:  yuexizeng
linkedin_username: yuexizeng
dribbble_username: 
facebook_username: yuexizeng
flickr_username:
instagram_username: yuexizeng
pinterest_username:
youtube_username: 
googleplus_username: 

plugins:
  - jekyll-feed

