# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Choosing the Right Chart for Your Data: A Quick Guide 
email: yuexizeng77@gmail.com  
description: "his a brief overview of common chart types and when to use them.  This would be a quick reference for studentsto select appropriate charts for their data without diving into advanced techniques." 
baseurl: "/yuexizeng.github.io" # the name of the repository 
url: "https://zyuexi2.github.io/yuexizeng.github.io" #  change this to "https://<your-github-username>.github.io"
image: https://unsplash.com/photos/6EnTPvPPL6I
author: Yuexi Zeng
copyright: YZ # Your initials or what you want the copyright to be.  Leave empty for no copyright
footer_description: 
        The default image for the blog post is from
        <a href="https://unsplash.com/photos/6EnTPvPPL6I" target="_blank"
        >Unsplash by Issac Smith</a>. Students in Stat 386 using this theme should replace both images 
        with their own.'


# Social media users names.  Leave fields blank that you don't want displayed
twitter_username: yuexizeng
github_username:  yuexizeng
linkedin_username: yuexizeng
dribbble_username: 
facebook_username: yuexizeng
flickr_username:
instagram_username: 
pinterest_username:
youtube_username: 
googleplus_username: yuexizeng

plugins:
  - jekyll-feed

